
package com.umg.api.ui;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.umg.api.model.Maestromodel;
import com.umg.api.service.MaestroService;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.ZoneId;
public class AgregarProfesor extends javax.swing.JFrame {
private Profesor pr1;

    public AgregarProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new com.umg.api.ui.PanelRound();
        panelRound1 = new com.umg.api.ui.PanelRound();
        btnCancelar = new javax.swing.JButton();
        panelRound3 = new com.umg.api.ui.PanelRound();
        btnAgregarProfesor = new javax.swing.JButton();
        txtEmailProfesor = new javax.swing.JTextField();
        lblEmailProfesor = new javax.swing.JLabel();
        lblSemestre1 = new javax.swing.JLabel();
        txtTelefonoProfesor = new javax.swing.JTextField();
        lblEspecialidad = new javax.swing.JLabel();
        cboCarrera = new javax.swing.JComboBox<>();
        lblEstado1 = new javax.swing.JLabel();
        cboEstado1 = new javax.swing.JComboBox<>();
        llbTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblNombreProfesor = new javax.swing.JLabel();
        txtaNombreProfesor = new javax.swing.JTextField();
        lblApellidoProfesor = new javax.swing.JLabel();
        txtaApellidoProfesor = new javax.swing.JTextField();
        lblFechaNacimientoProfesor = new javax.swing.JLabel();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(25);
        panelRound2.setRoundBottomRight(25);
        panelRound2.setRoundTopLeft(25);
        panelRound2.setRoundTopRight(25);

        panelRound1.setBackground(new java.awt.Color(179, 207, 229));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(74, 127, 167));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(26, 61, 99));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        btnAgregarProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarProfesor.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProfesor.setText("Agregar Profesor");
        btnAgregarProfesor.setBorderPainted(false);
        btnAgregarProfesor.setContentAreaFilled(false);
        btnAgregarProfesor.setFocusPainted(false);
        btnAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProfesor)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarProfesor)
                .addContainerGap())
        );

        txtEmailProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtEmailProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailProfesorActionPerformed(evt);
            }
        });

        lblEmailProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmailProfesor.setForeground(new java.awt.Color(10, 25, 49));
        lblEmailProfesor.setText("Email *");

        lblSemestre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSemestre1.setForeground(new java.awt.Color(10, 25, 49));
        lblSemestre1.setText("Telefono *");

        txtTelefonoProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtTelefonoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProfesorActionPerformed(evt);
            }
        });

        lblEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEspecialidad.setForeground(new java.awt.Color(10, 25, 49));
        lblEspecialidad.setText("Especialidad *");

        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería Informatica", "Ingeniería Civil", "Ingeniería Industrial", "Administración de Empresas", "Contabilidad y Finanzas", "Marketing", "Psicología", "Derecho", "Medicina", "Enfermería", "Arquitectura", "Diseño Grafico" }));
        cboCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        cboCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCarreraActionPerformed(evt);
            }
        });

        lblEstado1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado1.setForeground(new java.awt.Color(10, 25, 49));
        lblEstado1.setText("Estado");

        cboEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "inactivo", "suspendido", " " }));
        cboEstado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        llbTexto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        llbTexto1.setForeground(new java.awt.Color(10, 25, 49));
        llbTexto1.setText("Agregar Nuevo Profesor");

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Complete la información del nuevo profesor.");

        lblNombreProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreProfesor.setForeground(new java.awt.Color(10, 25, 49));
        lblNombreProfesor.setText("Nombre *");

        txtaNombreProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        lblApellidoProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellidoProfesor.setForeground(new java.awt.Color(10, 25, 49));
        lblApellidoProfesor.setText("Apellido *");

        txtaApellidoProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        lblFechaNacimientoProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaNacimientoProfesor.setForeground(new java.awt.Color(10, 25, 49));
        lblFechaNacimientoProfesor.setText("Fecha de nacimiento");

        jDateFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        jDateFechaNacimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelRound2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEspecialidad)
                                .addComponent(cboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmailProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSemestre1)
                                .addComponent(txtTelefonoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEstado1)
                                .addComponent(llbTexto1)
                                .addComponent(lblTexto2)
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtaApellidoProfesor)
                                    .addComponent(lblApellidoProfesor)
                                    .addComponent(lblNombreProfesor)
                                    .addComponent(txtaNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRound2Layout.createSequentialGroup()
                                    .addComponent(lblFechaNacimientoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(panelRound2Layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(llbTexto1)
                .addGap(5, 5, 5)
                .addComponent(lblTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreProfesor)
                .addGap(5, 5, 5)
                .addComponent(txtaNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidoProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtaApellidoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblEmailProfesor)
                .addGap(5, 5, 5)
                .addComponent(txtEmailProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSemestre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaNacimientoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEspecialidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado1)
                .addGap(5, 5, 5)
                .addComponent(cboEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailProfesorActionPerformed

    private void txtTelefonoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProfesorActionPerformed

    private void cboCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCarreraActionPerformed

    private void btnAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProfesorActionPerformed
  try {
        // Capturar valores de los campos
        String nombre = txtaNombreProfesor.getText().trim();
        String apellido = txtaApellidoProfesor.getText().trim();
        String email = txtEmailProfesor.getText().trim();
        String telefono = txtTelefonoProfesor.getText().trim();
        String especialidad = (String) cboCarrera.getSelectedItem();
        String estado = (String) cboEstado1.getSelectedItem();

        // Validar campos obligatorios
        if (nombre.isEmpty() || apellido.isEmpty() || email.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.");
            return;
        }

        // Validar formato de email
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un email válido.");
            return;
        }

        // Validar formato de teléfono
        if (!telefono.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El teléfono debe contener solo números.");
            return;
        }

        if (telefono.length() < 8) {
            JOptionPane.showMessageDialog(this, "El teléfono debe tener al menos 8 dígitos.");
            return;
        }

        // Crear objeto Maestro
        Maestromodel maestro = new Maestromodel();
        maestro.setNombre(nombre);
        maestro.setApellido(apellido);
        maestro.setEmail(email);
        maestro.setTelefono(telefono);
        maestro.setEspecialidad(especialidad);
        maestro.setEstado(estado);

        // CORRECCIÓN: Solo un bloque if para la fecha
        if (jDateFechaNacimiento.getDate() != null) {
            java.util.Date fechaSeleccionada = jDateFechaNacimiento.getDate();
            // Convertir a LocalDate
            LocalDate localDate = fechaSeleccionada.toInstant()
                                                 .atZone(java.time.ZoneId.systemDefault())
                                                 .toLocalDate();
            maestro.setFecha_nacimiento(localDate);
        }

        // Debug: mostrar lo que se va a enviar
        System.out.println("Datos del maestro:");
        System.out.println("Nombre: " + maestro.getNombre());
        System.out.println("Apellido: " + maestro.getApellido());
        System.out.println("Email: " + maestro.getEmail());
        System.out.println("Fecha Nacimiento: " + maestro.getFecha_nacimiento());

        // Guardar en la base de datos
        MaestroService service = new MaestroService();
        
        // Debug adicional: ver el JSON que se enviará
        try {
            ObjectMapper debugMapper = new ObjectMapper();
            debugMapper.registerModule(new JavaTimeModule());
            String json = debugMapper.writeValueAsString(maestro);
            System.out.println("JSON a enviar: " + json);
        } catch (Exception e) {
            System.out.println("Error al convertir a JSON: " + e.getMessage());
        }
        
        Maestromodel resultado = service.createMaestro(maestro);

        // Mensaje de éxito
        JOptionPane.showMessageDialog(this, "Profesor agregado correctamente.");

        // Actualizar tabla en panel Profesor
        if (pr1 != null) {
            pr1.loadProfesores();
        }

        // Limpiar campos
        txtaNombreProfesor.setText("");
        txtaApellidoProfesor.setText("");
        txtEmailProfesor.setText("");
        txtTelefonoProfesor.setText("");
        jDateFechaNacimiento.setDate(null);
        cboCarrera.setSelectedIndex(0);
        cboEstado1.setSelectedIndex(0);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "Error al agregar profesor: " + ex.getMessage() + 
            "\nDetalle completo: " + ex.toString());
        ex.printStackTrace();
    }
  pr1 = new Profesor();
    pr1.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnAgregarProfesorActionPerformed
    public void setP1(Profesor p1){
    this.pr1 = p1;
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
pr1 = new Profesor();
    pr1.setVisible(true);
    this.setVisible(false);
  
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProfesor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JComboBox<String> cboEstado1;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel lblApellidoProfesor;
    private javax.swing.JLabel lblEmailProfesor;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblFechaNacimientoProfesor;
    private javax.swing.JLabel lblNombreProfesor;
    private javax.swing.JLabel lblSemestre1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel llbTexto1;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound2;
    private com.umg.api.ui.PanelRound panelRound3;
    private javax.swing.JTextField txtEmailProfesor;
    private javax.swing.JTextField txtTelefonoProfesor;
    private javax.swing.JTextField txtaApellidoProfesor;
    private javax.swing.JTextField txtaNombreProfesor;
    // End of variables declaration//GEN-END:variables
}
