
package com.umg.api.ui;

import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.umg.api.model.Cursomodel;
import com.umg.api.service.CursoServer1;
import com.umg.api.model.Cursomodel;
import com.umg.api.service.CursoServer1;
import javax.swing.*;
public class AgregarCurso extends javax.swing.JFrame {
private Cursos cu1;

    public AgregarCurso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.umg.api.ui.PanelRound();
        llbTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        lblCodigoCurso = new javax.swing.JLabel();
        txtaCodigoCurso = new javax.swing.JTextField();
        lblIdProfesor = new javax.swing.JLabel();
        txtIdProfesor = new javax.swing.JTextField();
        lblSemestre = new javax.swing.JLabel();
        cboSemestre = new javax.swing.JComboBox<>();
        lblCreditos = new javax.swing.JLabel();
        cboCreditos = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        panelRound3 = new com.umg.api.ui.PanelRound();
        btnAgregarCurso = new javax.swing.JButton();
        panelRound2 = new com.umg.api.ui.PanelRound();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);

        llbTexto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        llbTexto1.setForeground(new java.awt.Color(10, 25, 49));
        llbTexto1.setText("Agregar Nuevo Curso");

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Complete la información del nuevo curso.");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(10, 25, 49));
        lblCurso.setText("Curso *");

        txtCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        lblCodigoCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodigoCurso.setForeground(new java.awt.Color(10, 25, 49));
        lblCodigoCurso.setText("Codigo del Curso *");

        txtaCodigoCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        lblIdProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdProfesor.setForeground(new java.awt.Color(10, 25, 49));
        lblIdProfesor.setText("Id Profesor");

        txtIdProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtIdProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProfesorActionPerformed(evt);
            }
        });

        lblSemestre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSemestre.setForeground(new java.awt.Color(10, 25, 49));
        lblSemestre.setText("Semestre");

        cboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er Semestre", "2do Semestre", "3er Semestre", "4to Semestre", "5to Semestre", "8vo Semestre", "9no Semestre", "10mo Semestre" }));
        cboSemestre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        lblCreditos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCreditos.setForeground(new java.awt.Color(10, 25, 49));
        lblCreditos.setText("Creditos *");

        cboCreditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cboCreditos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(10, 25, 49));
        lblEstado.setText("Estado");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "inactivo" }));
        cboEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));

        panelRound3.setBackground(new java.awt.Color(26, 61, 99));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        btnAgregarCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCurso.setText("Agregar Curso");
        btnAgregarCurso.setBorderPainted(false);
        btnAgregarCurso.setContentAreaFilled(false);
        btnAgregarCurso.setFocusPainted(false);
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarCurso)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarCurso)
                .addContainerGap())
        );

        panelRound2.setBackground(new java.awt.Color(179, 207, 229));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(74, 127, 167));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTexto2)
                            .addComponent(llbTexto1))
                        .addGap(94, 94, 94))
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCodigoCurso)
                        .addComponent(lblCurso)
                        .addComponent(lblIdProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboCreditos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstado)
                        .addComponent(lblSemestre)
                        .addComponent(lblCreditos)
                        .addComponent(cboSemestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboEstado, 0, 320, Short.MAX_VALUE)
                        .addComponent(txtIdProfesor)
                        .addComponent(txtaCodigoCurso)
                        .addComponent(txtCurso)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(llbTexto1)
                .addGap(5, 5, 5)
                .addComponent(lblTexto2)
                .addGap(18, 18, 18)
                .addComponent(lblCurso)
                .addGap(5, 5, 5)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigoCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtaCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdProfesor)
                .addGap(5, 5, 5)
                .addComponent(txtIdProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSemestre)
                .addGap(5, 5, 5)
                .addComponent(cboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCreditos)
                .addGap(5, 5, 5)
                .addComponent(cboCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProfesorActionPerformed

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed
       try {
        // Validar campos obligatorios
        if (txtCurso.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del curso es obligatorio");
            return;
        }
        if (txtaCodigoCurso.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El código del curso es obligatorio");
            return;
        }
        
        // Crear objeto curso
        Cursomodel curso = new Cursomodel();
        curso.setNombre(txtCurso.getText().trim());
        curso.setCodigo(Integer.parseInt(txtaCodigoCurso.getText().trim()));
        
        // Campos opcionales (solo si no están vacíos)
        if (!txtIdProfesor.getText().trim().isEmpty()) {
            curso.setCatedraticoCod(Integer.parseInt(txtIdProfesor.getText().trim()));
        }
        
        curso.setSemestre(cboSemestre.getSelectedItem().toString());
        curso.setCreditos(Integer.parseInt(cboCreditos.getSelectedItem().toString()));
        
        // Manejo correcto del estado
        String estadoSeleccionado = cboEstado.getSelectedItem().toString();
        if (estadoSeleccionado.equals("Seleccione estado")) {
            curso.setEstado_curso(null);
        } else {
            curso.setEstado_curso(estadoSeleccionado);
        }

        // Llamar al servicio
        CursoServer1 service = new CursoServer1();
        Cursomodel cursoCreado = service.createCurso(curso);

        // SI LLEGA AQUÍ, EL CURSO SE CREÓ EXITOSAMENTE
        JOptionPane.showMessageDialog(this, "Curso creado exitosamente: " + cursoCreado.getNombre());

        // Actualizar tabla en JFrame Cursos si está disponible
        if (cu1 != null) {
            cu1.cargarDatos();
        }

        this.dispose(); // Cerrar ventana después de agregar
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique que los campos numéricos contengan valores válidos");
    } catch (Exception e) {
        // ESTE ES EL ERROR QUE ESTÁS VIENDO - El servidor devuelve JSON en lugar de objeto
        JOptionPane.showMessageDialog(this, "Error al procesar respuesta del servidor: " + e.getMessage());
        
        // Pero el curso SÍ se creó, así que cerramos la ventana igualmente
        if (cu1 != null) {
            cu1.cargarDatos(); // Actualizar la tabla para ver el nuevo curso
        }
        this.dispose(); // Cerrar la ventana
    }
                   
    }//GEN-LAST:event_btnAgregarCursoActionPerformed
    public void setP1(Cursos p1){
    this.cu1 = p1;
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    cu1 = new Cursos();
    cu1.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cboCreditos;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboSemestre;
    private javax.swing.JLabel lblCodigoCurso;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdProfesor;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel llbTexto1;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound2;
    private com.umg.api.ui.PanelRound panelRound3;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtIdProfesor;
    private javax.swing.JTextField txtaCodigoCurso;
    // End of variables declaration//GEN-END:variables
}
