/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.api.ui;
import com.umg.api.model.Asignacionmodel;
import com.umg.api.service.AsignacionService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class Asignacion extends javax.swing.JPanel {
  /*private DefaultTableModel model;
    private AsignacionService service = new AsignacionService();
    private TableRowSorter<DefaultTableModel> rowSorter;*/


    public Asignacion() {
        initComponents();
    }
       /* model = new DefaultTableModel(
            new String[]{"studentID", "courseID", "fechaInscripcion", "estado"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.umg.api.ui.PanelRound();
        panelRound3 = new com.umg.api.ui.PanelRound();
        btnAgregarAsignacion = new javax.swing.JButton();
        panelRound4 = new com.umg.api.ui.PanelRound();
        btnEliminarAsignacion = new javax.swing.JButton();
        panelRound5 = new com.umg.api.ui.PanelRound();
        btnEditarAsignacion = new javax.swing.JButton();
        panelRound6 = new com.umg.api.ui.PanelRound();
        btnBuscarAsignacion = new javax.swing.JButton();
        txtBuscarAsignacion = new javax.swing.JTextField();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        JTableAsignaciones = new javax.swing.JScrollPane();
        jTableEstudiante = new javax.swing.JTable();
        panelRound7 = new com.umg.api.ui.PanelRound();
        btnConsultarAsignacion = new javax.swing.JButton();

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(179, 207, 229));
        panelRound3.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        btnAgregarAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarAsignacion.setText("agregar");
        btnAgregarAsignacion.setBorderPainted(false);
        btnAgregarAsignacion.setContentAreaFilled(false);
        btnAgregarAsignacion.setFocusPainted(false);
        btnAgregarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarAsignacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarAsignacion)
                .addContainerGap())
        );

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 90, -1));

        panelRound4.setBackground(new java.awt.Color(179, 207, 229));
        panelRound4.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        btnEliminarAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarAsignacion.setText("eliminar");
        btnEliminarAsignacion.setBorderPainted(false);
        btnEliminarAsignacion.setContentAreaFilled(false);
        btnEliminarAsignacion.setFocusPainted(false);
        btnEliminarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(btnEliminarAsignacion)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarAsignacion)
                .addContainerGap())
        );

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, -1));

        panelRound5.setBackground(new java.awt.Color(179, 207, 229));
        panelRound5.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        btnEditarAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarAsignacion.setText("Editar");
        btnEditarAsignacion.setBorderPainted(false);
        btnEditarAsignacion.setContentAreaFilled(false);
        btnEditarAsignacion.setFocusPainted(false);
        btnEditarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarAsignacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, -1));

        panelRound6.setBackground(new java.awt.Color(179, 207, 229));
        panelRound6.setPreferredSize(new java.awt.Dimension(942, 33));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarAsignacion.setText("Buscar");
        btnBuscarAsignacion.setBorderPainted(false);
        btnBuscarAsignacion.setContentAreaFilled(false);
        btnBuscarAsignacion.setFocusPainted(false);
        btnBuscarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignacionActionPerformed(evt);
            }
        });
        panelRound6.add(btnBuscarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        txtBuscarAsignacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtBuscarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarAsignacionActionPerformed(evt);
            }
        });
        panelRound6.add(txtBuscarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 20));

        panelRound1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 970, 40));

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Administra tareas y proyectos");
        panelRound1.add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(10, 25, 49));
        lblTexto1.setText("Gestión de Asignaciones");
        panelRound1.add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTableEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 207, 229)));
        jTableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableAsignaciones.setViewportView(jTableEstudiante);

        panelRound1.add(JTableAsignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 970, 220));

        panelRound7.setBackground(new java.awt.Color(179, 207, 229));
        panelRound7.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound7.setRoundBottomLeft(15);
        panelRound7.setRoundBottomRight(15);
        panelRound7.setRoundTopLeft(15);
        panelRound7.setRoundTopRight(15);

        btnConsultarAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultarAsignacion.setText("Consultar");
        btnConsultarAsignacion.setBorderPainted(false);
        btnConsultarAsignacion.setContentAreaFilled(false);
        btnConsultarAsignacion.setFocusPainted(false);
        btnConsultarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarAsignacion)
                .addContainerGap())
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarAsignacion)
                .addContainerGap())
        );

        panelRound1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAsignacionActionPerformed

    private void txtBuscarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarAsignacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarAsignacionActionPerformed

    private void btnEditarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAsignacionActionPerformed
        EditarCurso h1 = new EditarCurso();
        h1.setVisible(true);
    }//GEN-LAST:event_btnEditarAsignacionActionPerformed

    private void btnAgregarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAsignacionActionPerformed
        AgregarAsignacion g1 = new AgregarAsignacion();
        g1.setVisible(true);
    }//GEN-LAST:event_btnAgregarAsignacionActionPerformed

    private void btnEliminarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAsignacionActionPerformed
        EliminarAsignacion f1 = new EliminarAsignacion();
        f1.setVisible(true);
    }//GEN-LAST:event_btnEliminarAsignacionActionPerformed

    private void btnConsultarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAsignacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarAsignacionActionPerformed
    
   /* public void loadAsignaciones() {
        try {
            List<Asignacionmodel> list = service.getAsignacionmodels();
            System.out.println("Profesores encontrados: " + list.size());

            model.setRowCount(0); // limpiar tabla

            for (Asignacionmodel m : list) {
                model.addRow(new Object[]{
                    m.getStudentID(),
                    m.getCourseID(),
                    m.getFechaInscripcion(),
                    m.getEstado(),
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar profesores: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void filtrarTabla() {
        String filtro = txtBuscarAsignacion.getText().trim();
        if (filtro.length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro));
        }
    }
    
    public void loadCustomers(){
    try{
    model.setRowCount((0));
    List<Asignacionmodel> list = service.getAsignacionmodels();
    for (Asignacionmodel c : list){
        model.addRow(new Object[]{c.getStudentID(), c.getCourseID(), c.getFechaInscripcion(), c.getEstado()});
    }
    }catch (Exception ex){
      JOptionPane.showMessageDialog(this, "Error cargando clientes:" + ex.getMessage());
    }
    
}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JTableAsignaciones;
    private javax.swing.JButton btnAgregarAsignacion;
    private javax.swing.JButton btnBuscarAsignacion;
    private javax.swing.JButton btnConsultarAsignacion;
    private javax.swing.JButton btnEditarAsignacion;
    private javax.swing.JButton btnEliminarAsignacion;
    private javax.swing.JTable jTableEstudiante;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound3;
    private com.umg.api.ui.PanelRound panelRound4;
    private com.umg.api.ui.PanelRound panelRound5;
    private com.umg.api.ui.PanelRound panelRound6;
    private com.umg.api.ui.PanelRound panelRound7;
    private javax.swing.JTextField txtBuscarAsignacion;
    // End of variables declaration//GEN-END:variables
}
