/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.api.ui;

/**
 *
 * @author mayno
 */
public class Estudiante extends javax.swing.JPanel {

    /**
     * Creates new form Estudiante
     */
    public Estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.umg.api.ui.PanelRound();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        panelRound3 = new com.umg.api.ui.PanelRound();
        btnAgregarEstudiante = new javax.swing.JButton();
        panelRound4 = new com.umg.api.ui.PanelRound();
        btnEliminarEstudiante = new javax.swing.JButton();
        panelRound5 = new com.umg.api.ui.PanelRound();
        btnEditarEstudiante = new javax.swing.JButton();
        panelRound6 = new com.umg.api.ui.PanelRound();
        btnBuscarEstudiante = new javax.swing.JButton();
        txtBuscarEstudiante = new javax.swing.JTextField();
        JTableEstudiantes = new javax.swing.JScrollPane();
        jTableEstudiante = new javax.swing.JTable();
        panelRound7 = new com.umg.api.ui.PanelRound();
        btnConsultarEstudiante = new javax.swing.JButton();

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(10, 25, 49));
        lblTexto1.setText("Gestión de Estudiantes");
        panelRound1.add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Administra la información de los estudiantes");
        panelRound1.add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        panelRound3.setBackground(new java.awt.Color(179, 207, 229));
        panelRound3.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        btnAgregarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarEstudiante.setText("agregar");
        btnAgregarEstudiante.setBorderPainted(false);
        btnAgregarEstudiante.setContentAreaFilled(false);
        btnAgregarEstudiante.setFocusPainted(false);
        btnAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarEstudiante)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarEstudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 90, -1));

        panelRound4.setBackground(new java.awt.Color(179, 207, 229));
        panelRound4.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        btnEliminarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarEstudiante.setText("eliminar");
        btnEliminarEstudiante.setBorderPainted(false);
        btnEliminarEstudiante.setContentAreaFilled(false);
        btnEliminarEstudiante.setFocusPainted(false);
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(btnEliminarEstudiante)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarEstudiante)
                .addContainerGap())
        );

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, -1));

        panelRound5.setBackground(new java.awt.Color(179, 207, 229));
        panelRound5.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        btnEditarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarEstudiante.setText("Editar");
        btnEditarEstudiante.setBorderPainted(false);
        btnEditarEstudiante.setContentAreaFilled(false);
        btnEditarEstudiante.setFocusPainted(false);
        btnEditarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarEstudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, -1));

        panelRound6.setBackground(new java.awt.Color(179, 207, 229));
        panelRound6.setPreferredSize(new java.awt.Dimension(942, 33));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarEstudiante.setText("Buscar");
        btnBuscarEstudiante.setBorderPainted(false);
        btnBuscarEstudiante.setContentAreaFilled(false);
        btnBuscarEstudiante.setFocusPainted(false);
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });
        panelRound6.add(btnBuscarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        txtBuscarEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarEstudianteActionPerformed(evt);
            }
        });
        panelRound6.add(txtBuscarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 20));

        panelRound1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 970, 40));

        jTableEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 207, 229)));
        jTableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableEstudiantes.setViewportView(jTableEstudiante);

        panelRound1.add(JTableEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 970, 220));

        panelRound7.setBackground(new java.awt.Color(179, 207, 229));
        panelRound7.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound7.setRoundBottomLeft(15);
        panelRound7.setRoundBottomRight(15);
        panelRound7.setRoundTopLeft(15);
        panelRound7.setRoundTopRight(15);

        btnConsultarEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultarEstudiante.setText("Consultar");
        btnConsultarEstudiante.setBorderPainted(false);
        btnConsultarEstudiante.setContentAreaFilled(false);
        btnConsultarEstudiante.setFocusPainted(false);
        btnConsultarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarEstudiante)
                .addContainerGap())
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarEstudiante)
                .addContainerGap())
        );

        panelRound1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstudianteActionPerformed
     EditarEstudiante ed1 = new EditarEstudiante();
     ed1.setVisible(true);
    }//GEN-LAST:event_btnEditarEstudianteActionPerformed

    private void btnAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstudianteActionPerformed
     AgregarEstudiante a1 = new AgregarEstudiante();
     a1.setVisible(true);
    }//GEN-LAST:event_btnAgregarEstudianteActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        EliminarEstudiante c1 = new EliminarEstudiante();
        c1.setVisible(true);
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void txtBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarEstudianteActionPerformed

    private void btnConsultarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JTableEstudiantes;
    private javax.swing.JButton btnAgregarEstudiante;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnConsultarEstudiante;
    private javax.swing.JButton btnEditarEstudiante;
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JTable jTableEstudiante;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound3;
    private com.umg.api.ui.PanelRound panelRound4;
    private com.umg.api.ui.PanelRound panelRound5;
    private com.umg.api.ui.PanelRound panelRound6;
    private com.umg.api.ui.PanelRound panelRound7;
    private javax.swing.JTextField txtBuscarEstudiante;
    // End of variables declaration//GEN-END:variables
}
