/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.api.ui;



/**
 *
 * @author mayno
 */
public class Notas extends javax.swing.JPanel {


    public Notas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.umg.api.ui.PanelRound();
        panelRound3 = new com.umg.api.ui.PanelRound();
        btnAgregarNota = new javax.swing.JButton();
        panelRound4 = new com.umg.api.ui.PanelRound();
        btnConsultarNota = new javax.swing.JButton();
        panelRound5 = new com.umg.api.ui.PanelRound();
        btnEditarNota = new javax.swing.JButton();
        panelRound6 = new com.umg.api.ui.PanelRound();
        btnBuscarProfesor = new javax.swing.JButton();
        txtBuscarProfesor = new javax.swing.JTextField();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        jTableProfesores = new javax.swing.JScrollPane();
        jTableNotas = new javax.swing.JTable();
        panelRound7 = new com.umg.api.ui.PanelRound();
        btnEliminarNota = new javax.swing.JButton();

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(179, 207, 229));
        panelRound3.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        btnAgregarNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarNota.setText("agregar");
        btnAgregarNota.setBorderPainted(false);
        btnAgregarNota.setContentAreaFilled(false);
        btnAgregarNota.setFocusPainted(false);
        btnAgregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarNota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarNota)
                .addContainerGap())
        );

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 90, -1));

        panelRound4.setBackground(new java.awt.Color(179, 207, 229));
        panelRound4.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        btnConsultarNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultarNota.setText("Consultar");
        btnConsultarNota.setBorderPainted(false);
        btnConsultarNota.setContentAreaFilled(false);
        btnConsultarNota.setFocusPainted(false);
        btnConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarNota)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultarNota)
                .addContainerGap())
        );

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 90, -1));

        panelRound5.setBackground(new java.awt.Color(179, 207, 229));
        panelRound5.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        btnEditarNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarNota.setText("Editar");
        btnEditarNota.setBorderPainted(false);
        btnEditarNota.setContentAreaFilled(false);
        btnEditarNota.setFocusPainted(false);
        btnEditarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarNota, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarNota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, -1));

        panelRound6.setBackground(new java.awt.Color(179, 207, 229));
        panelRound6.setPreferredSize(new java.awt.Dimension(942, 33));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProfesor.setText("Buscar");
        btnBuscarProfesor.setBorderPainted(false);
        btnBuscarProfesor.setContentAreaFilled(false);
        btnBuscarProfesor.setFocusPainted(false);
        btnBuscarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProfesorActionPerformed(evt);
            }
        });
        panelRound6.add(btnBuscarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        txtBuscarProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtBuscarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProfesorActionPerformed(evt);
            }
        });
        panelRound6.add(txtBuscarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 20));

        panelRound1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 970, 40));

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(10, 25, 49));
        lblTexto1.setText("Gestión de Notas");
        panelRound1.add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Administra las calificaciones del estudiante. ");
        panelRound1.add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTableNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 165)));
        jTableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProfesores.setViewportView(jTableNotas);

        panelRound1.add(jTableProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 970, 220));

        panelRound7.setBackground(new java.awt.Color(179, 207, 229));
        panelRound7.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound7.setRoundBottomLeft(15);
        panelRound7.setRoundBottomRight(15);
        panelRound7.setRoundTopLeft(15);
        panelRound7.setRoundTopRight(15);

        btnEliminarNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarNota.setText("eliminar");
        btnEliminarNota.setBorderPainted(false);
        btnEliminarNota.setContentAreaFilled(false);
        btnEliminarNota.setFocusPainted(false);
        btnEliminarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(btnEliminarNota)
                .addContainerGap())
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarNota)
                .addContainerGap())
        );

        panelRound1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProfesorActionPerformed

    private void txtBuscarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProfesorActionPerformed

    private void btnConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarNotaActionPerformed

    }//GEN-LAST:event_btnConsultarNotaActionPerformed

    private void btnEditarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNotaActionPerformed
     EditarNotas y1 = new EditarNotas();
     y1.setVisible(true);
    }//GEN-LAST:event_btnEditarNotaActionPerformed

    private void btnAgregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaActionPerformed
     AgregarNotas nt1 = new AgregarNotas();
     nt1.setVisible(true);
    }//GEN-LAST:event_btnAgregarNotaActionPerformed

    private void btnEliminarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarNotaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNota;
    private javax.swing.JButton btnBuscarProfesor;
    private javax.swing.JButton btnConsultarNota;
    private javax.swing.JButton btnEditarNota;
    private javax.swing.JButton btnEliminarNota;
    private javax.swing.JTable jTableNotas;
    private javax.swing.JScrollPane jTableProfesores;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound3;
    private com.umg.api.ui.PanelRound panelRound4;
    private com.umg.api.ui.PanelRound panelRound5;
    private com.umg.api.ui.PanelRound panelRound6;
    private com.umg.api.ui.PanelRound panelRound7;
    private javax.swing.JTextField txtBuscarProfesor;
    // End of variables declaration//GEN-END:variables

}
