/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.api.ui;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author mayno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        Estudiante p1 = new Estudiante();
        p1.setSize(1015, 404);
        p1.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());       
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
         ImageIcon portada = new ImageIcon(getClass().getResource("/img/portada.png"));
    Image imagenEscalada = portada.getImage().getScaledInstance(
    lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
    lblLogo.setIcon(new ImageIcon(imagenEscalada));
    
    ImageIcon estudiantes = new ImageIcon(getClass().getResource("/img/estudiantes.png"));
    Image imagenEstudiantes = estudiantes.getImage().getScaledInstance(
    lblEstudiantesIcono.getWidth(), lblEstudiantesIcono.getHeight(), Image.SCALE_SMOOTH);
    lblEstudiantesIcono.setIcon(new ImageIcon(imagenEstudiantes));
    
        ImageIcon profesor = new ImageIcon(getClass().getResource("/img/profesor.png"));
    Image imagenProfesor = profesor.getImage().getScaledInstance(
    lblProfesorIcono.getWidth(), lblProfesorIcono.getHeight(), Image.SCALE_SMOOTH);
    lblProfesorIcono.setIcon(new ImageIcon(imagenProfesor));
    
    ImageIcon cursos = new ImageIcon(getClass().getResource("/img/cursos.png"));
    Image imagenCursos = cursos.getImage().getScaledInstance(
    lblCursosIcono.getWidth(), lblCursosIcono.getHeight(), Image.SCALE_SMOOTH);
    lblCursosIcono.setIcon(new ImageIcon(imagenCursos));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.umg.api.ui.PanelRound();
        lblLogo = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        panelRound2 = new com.umg.api.ui.PanelRound();
        lblEstudiantes = new javax.swing.JLabel();
        lblEstudiantesIcono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound3 = new com.umg.api.ui.PanelRound();
        lblProfersores = new javax.swing.JLabel();
        lblProfesorIcono = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelRound4 = new com.umg.api.ui.PanelRound();
        lblCursosIcono = new javax.swing.JLabel();
        lblCursos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound5 = new com.umg.api.ui.PanelRound();
        panelRound6 = new com.umg.api.ui.PanelRound();
        btnEstudiantesVista = new javax.swing.JButton();
        panelRound7 = new com.umg.api.ui.PanelRound();
        btnProfesoresVista = new javax.swing.JButton();
        panelRound8 = new com.umg.api.ui.PanelRound();
        btnCursosVista = new javax.swing.JButton();
        panelRound9 = new com.umg.api.ui.PanelRound();
        btnAsignacionesVista = new javax.swing.JButton();
        panelRound10 = new com.umg.api.ui.PanelRound();
        btnNotasVista = new javax.swing.JButton();
        content = new com.umg.api.ui.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(214, 230, 242));

        lblLogo.setText("jLabel1");

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(10, 25, 49));
        lblTexto1.setText("Sistema Academico Universitario");

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Panel de Administración");

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(25);
        panelRound2.setRoundBottomRight(25);
        panelRound2.setRoundTopLeft(25);
        panelRound2.setRoundTopRight(25);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstudiantes.setForeground(new java.awt.Color(74, 127, 167));
        lblEstudiantes.setText("Estudiantes");
        panelRound2.add(lblEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblEstudiantesIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/estudiantes.png"))); // NOI18N
        panelRound2.add(lblEstudiantesIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel3.setText("jLabel3");
        panelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 70, 40));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(25);
        panelRound3.setRoundBottomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfersores.setForeground(new java.awt.Color(74, 127, 167));
        lblProfersores.setText("Profersores");
        panelRound3.add(lblProfersores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblProfesorIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/profesor.png"))); // NOI18N
        panelRound3.add(lblProfesorIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel4.setText("jLabel3");
        panelRound3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 70, 40));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(25);
        panelRound4.setRoundBottomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCursosIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cursos.png"))); // NOI18N
        panelRound4.add(lblCursosIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        lblCursos.setForeground(new java.awt.Color(74, 127, 167));
        lblCursos.setText("Cursos");
        panelRound4.add(lblCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel5.setText("jLabel3");
        panelRound4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 70, 40));

        panelRound5.setBackground(new java.awt.Color(179, 207, 229));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setRoundBottomLeft(25);
        panelRound6.setRoundBottomRight(25);
        panelRound6.setRoundTopLeft(25);
        panelRound6.setRoundTopRight(25);

        btnEstudiantesVista.setForeground(new java.awt.Color(74, 127, 167));
        btnEstudiantesVista.setText("Estudiantes");
        btnEstudiantesVista.setBorderPainted(false);
        btnEstudiantesVista.setContentAreaFilled(false);
        btnEstudiantesVista.setFocusPainted(false);
        btnEstudiantesVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEstudiantesVista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEstudiantesVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound7.setBackground(new java.awt.Color(255, 255, 255));
        panelRound7.setRoundBottomLeft(25);
        panelRound7.setRoundBottomRight(25);
        panelRound7.setRoundTopLeft(25);
        panelRound7.setRoundTopRight(25);

        btnProfesoresVista.setForeground(new java.awt.Color(74, 127, 167));
        btnProfesoresVista.setText("Profesores");
        btnProfesoresVista.setBorderPainted(false);
        btnProfesoresVista.setContentAreaFilled(false);
        btnProfesoresVista.setFocusPainted(false);
        btnProfesoresVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(btnProfesoresVista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnProfesoresVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound8.setBackground(new java.awt.Color(255, 255, 255));
        panelRound8.setRoundBottomLeft(25);
        panelRound8.setRoundBottomRight(25);
        panelRound8.setRoundTopLeft(25);
        panelRound8.setRoundTopRight(25);

        btnCursosVista.setForeground(new java.awt.Color(74, 127, 167));
        btnCursosVista.setText("Cursos");
        btnCursosVista.setBorderPainted(false);
        btnCursosVista.setContentAreaFilled(false);
        btnCursosVista.setFocusPainted(false);
        btnCursosVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCursosVista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCursosVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setRoundBottomLeft(25);
        panelRound9.setRoundBottomRight(25);
        panelRound9.setRoundTopLeft(25);
        panelRound9.setRoundTopRight(25);

        btnAsignacionesVista.setForeground(new java.awt.Color(74, 127, 167));
        btnAsignacionesVista.setText("Asignaciones");
        btnAsignacionesVista.setBorderPainted(false);
        btnAsignacionesVista.setContentAreaFilled(false);
        btnAsignacionesVista.setFocusPainted(false);
        btnAsignacionesVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionesVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAsignacionesVista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAsignacionesVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound10.setBackground(new java.awt.Color(255, 255, 255));
        panelRound10.setRoundBottomLeft(25);
        panelRound10.setRoundBottomRight(25);
        panelRound10.setRoundTopLeft(25);
        panelRound10.setRoundTopRight(25);

        btnNotasVista.setForeground(new java.awt.Color(74, 127, 167));
        btnNotasVista.setText("Notas");
        btnNotasVista.setBorderPainted(false);
        btnNotasVista.setContentAreaFilled(false);
        btnNotasVista.setFocusPainted(false);
        btnNotasVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasVistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNotasVista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNotasVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTexto2))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lblTexto1))
                            .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(lblTexto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto2))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudiantesVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesVistaActionPerformed
        Estudiante p1 = new Estudiante();
        p1.setSize(1015, 404);
        p1.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEstudiantesVistaActionPerformed

    private void btnProfesoresVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresVistaActionPerformed
        Profesor p2 = new Profesor();
        p2.setSize(1015, 404);
        p2.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnProfesoresVistaActionPerformed

    private void btnCursosVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosVistaActionPerformed
        Cursos p3 = new Cursos();
        p3.setSize(1015, 404);
        p3.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCursosVistaActionPerformed

    private void btnAsignacionesVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionesVistaActionPerformed
        Asignacion p4 = new Asignacion();
        p4.setSize(1015, 404);
        p4.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p4, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAsignacionesVistaActionPerformed

    private void btnNotasVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasVistaActionPerformed
        Notas p5 = new Notas();
        p5.setSize(1015, 404);
        p5.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p5, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnNotasVistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignacionesVista;
    private javax.swing.JButton btnCursosVista;
    private javax.swing.JButton btnEstudiantesVista;
    private javax.swing.JButton btnNotasVista;
    private javax.swing.JButton btnProfesoresVista;
    private com.umg.api.ui.PanelRound content;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCursos;
    private javax.swing.JLabel lblCursosIcono;
    private javax.swing.JLabel lblEstudiantes;
    private javax.swing.JLabel lblEstudiantesIcono;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblProfersores;
    private javax.swing.JLabel lblProfesorIcono;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound10;
    private com.umg.api.ui.PanelRound panelRound2;
    private com.umg.api.ui.PanelRound panelRound3;
    private com.umg.api.ui.PanelRound panelRound4;
    private com.umg.api.ui.PanelRound panelRound5;
    private com.umg.api.ui.PanelRound panelRound6;
    private com.umg.api.ui.PanelRound panelRound7;
    private com.umg.api.ui.PanelRound panelRound8;
    private com.umg.api.ui.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
}
