
package com.umg.api.ui;
import com.umg.api.model.Maestromodel;
import com.umg.api.service.MaestroService;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class Profesor extends javax.swing.JPanel {
  private DefaultTableModel model;
    private MaestroService service = new MaestroService();
    private TableRowSorter<DefaultTableModel> rowSorter;
    public Profesor() {
         initComponents();
        
     model = new DefaultTableModel(
            new String[]{"ID", "Nombre", "Apellido", "Email", "Especialidad", "Telefono", "Estado", "Fecha de trabajo que inicio"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableProfesor.setModel(model);
        
        rowSorter = new TableRowSorter<>(model);
        jTableProfesor.setRowSorter(rowSorter);

        loadProfesores();
    }

       /* jtProfesor.setModel(model);

        jtProfesor.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                fillFieldsFromSelectedRow();
            }
        });*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.umg.api.ui.PanelRound();
        panelRound3 = new com.umg.api.ui.PanelRound();
        btnAgregarProfesor = new javax.swing.JButton();
        panelRound4 = new com.umg.api.ui.PanelRound();
        btnActualizarProfesor = new javax.swing.JButton();
        panelRound5 = new com.umg.api.ui.PanelRound();
        btnEditarProfesor = new javax.swing.JButton();
        panelRound6 = new com.umg.api.ui.PanelRound();
        btnBuscarProfesors = new javax.swing.JButton();
        txtBuscarProfesors = new javax.swing.JTextField();
        JTableEstudiantes = new javax.swing.JScrollPane();
        jTableProfesor = new javax.swing.JTable();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        panelRound7 = new com.umg.api.ui.PanelRound();
        btnEliminarProfesor1 = new javax.swing.JButton();

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(179, 207, 229));
        panelRound3.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound3.setRoundBottomLeft(15);
        panelRound3.setRoundBottomRight(15);
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        btnAgregarProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarProfesor.setText("agregar");
        btnAgregarProfesor.setBorderPainted(false);
        btnAgregarProfesor.setContentAreaFilled(false);
        btnAgregarProfesor.setFocusPainted(false);
        btnAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarProfesor)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarProfesor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 90, -1));

        panelRound4.setBackground(new java.awt.Color(179, 207, 229));
        panelRound4.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        btnActualizarProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarProfesor.setText("Actualizar");
        btnActualizarProfesor.setBorderPainted(false);
        btnActualizarProfesor.setContentAreaFilled(false);
        btnActualizarProfesor.setFocusPainted(false);
        btnActualizarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizarProfesor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizarProfesor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 90, -1));

        panelRound5.setBackground(new java.awt.Color(179, 207, 229));
        panelRound5.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        btnEditarProfesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarProfesor.setText("Editar");
        btnEditarProfesor.setBorderPainted(false);
        btnEditarProfesor.setContentAreaFilled(false);
        btnEditarProfesor.setFocusPainted(false);
        btnEditarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarProfesor)
                .addContainerGap())
        );

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, -1));

        panelRound6.setBackground(new java.awt.Color(179, 207, 229));
        panelRound6.setPreferredSize(new java.awt.Dimension(942, 33));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarProfesors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProfesors.setText("Buscar");
        btnBuscarProfesors.setBorderPainted(false);
        btnBuscarProfesors.setContentAreaFilled(false);
        btnBuscarProfesors.setFocusPainted(false);
        btnBuscarProfesors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProfesorsActionPerformed(evt);
            }
        });
        panelRound6.add(btnBuscarProfesors, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        txtBuscarProfesors.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 127, 167)));
        txtBuscarProfesors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProfesorsActionPerformed(evt);
            }
        });
        panelRound6.add(txtBuscarProfesors, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 20));

        panelRound1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 970, 40));

        jTableProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 207, 229)));
        jTableProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableEstudiantes.setViewportView(jTableProfesor);

        panelRound1.add(JTableEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 970, 220));

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(10, 25, 49));
        lblTexto1.setText("Gestión de Profesores");
        panelRound1.add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblTexto2.setForeground(new java.awt.Color(74, 127, 167));
        lblTexto2.setText("Administra el cuerpo del docente");
        panelRound1.add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        panelRound7.setBackground(new java.awt.Color(179, 207, 229));
        panelRound7.setPreferredSize(new java.awt.Dimension(90, 35));
        panelRound7.setRoundBottomLeft(15);
        panelRound7.setRoundBottomRight(15);
        panelRound7.setRoundTopLeft(15);
        panelRound7.setRoundTopRight(15);

        btnEliminarProfesor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarProfesor1.setText("eliminar");
        btnEliminarProfesor1.setBorderPainted(false);
        btnEliminarProfesor1.setContentAreaFilled(false);
        btnEliminarProfesor1.setFocusPainted(false);
        btnEliminarProfesor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProfesor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarProfesor1)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarProfesor1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProfesorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProfesorsActionPerformed
       //loadProfesores();  // carga todos los profesores
    filtrarTabla(); 
    }//GEN-LAST:event_btnBuscarProfesorsActionPerformed

    private void txtBuscarProfesorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProfesorsActionPerformed
filtrarTabla();   
    }//GEN-LAST:event_txtBuscarProfesorsActionPerformed

    private void btnAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProfesorActionPerformed
AgregarProfesor z1 = new AgregarProfesor();
    z1.setVisible(true);
    z1.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            loadProfesores(); // Recargar la tabla después de agregar
        }
    });
     
    }//GEN-LAST:event_btnAgregarProfesorActionPerformed

    private void btnEditarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProfesorActionPerformed
    int fila = jTableProfesor.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un profesor para editar");
        return;
    }

    // Obtener el índice real de la fila (considerando el filtro)
    int modelRow = jTableProfesor.convertRowIndexToModel(fila);
    String profesor = (String) model.getValueAt(modelRow, 1); // Columna 1 es el nombre
    
    EditarProfesor y1 = new EditarProfesor(profesor); // Cambiar a usar nombre en lugar de id
    y1.setVisible(true);
    
    // Agregar listener para cuando se cierre la ventana de editar
    y1.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            loadProfesores();
        }
    });


    }//GEN-LAST:event_btnEditarProfesorActionPerformed

    private void btnActualizarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProfesorActionPerformed
loadCustomers();
        
    }//GEN-LAST:event_btnActualizarProfesorActionPerformed

    private void btnEliminarProfesor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProfesor1ActionPerformed
                                                   
    int fila = jTableProfesor.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un profesor para eliminar");
        return;
    }

    int modelRow = jTableProfesor.convertRowIndexToModel(fila);
    String nombre = (String) model.getValueAt(modelRow, 1);
    
    EliminarProfesor eliminarFrame = new EliminarProfesor(nombre);
    eliminarFrame.setVentanaProfesor(this); // ← Cambiado a setVentanaProfesor
    eliminarFrame.setVisible(true);
    }//GEN-LAST:event_btnEliminarProfesor1ActionPerformed
  public void loadProfesores() {
        try {
            List<Maestromodel> list = service.getMaestros();
            System.out.println("Profesores encontrados: " + list.size());

            model.setRowCount(0); // limpiar tabla

            for (Maestromodel m : list) {
                model.addRow(new Object[]{
                    m.getId_catedratico(),
                    m.getNombre(),
                    m.getApellido(),
                    m.getEmail(),
                    m.getEspecialidad(),
                    m.getTelefono(),
                    m.getEstado(),
                    m.getFecha_nacimiento()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar profesores: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void filtrarTabla() {
        String filtro = txtBuscarProfesors.getText().trim();
        if (filtro.length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro));
        }
    }
    public void loadCustomers(){
    try{
    model.setRowCount((0));
    List<Maestromodel> list = service.getMaestros();
    for (Maestromodel c : list){
        model.addRow(new Object[]{c.getId_catedratico(), c.getNombre(), c.getApellido(), c.getEmail(), c.getEspecialidad(), c.getTelefono(), c.getEstado(), c.getFecha_ingreso()});
    }
    }catch (Exception ex){
      JOptionPane.showMessageDialog(this, "Error cargando clientes:" + ex.getMessage());
    }
    
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JTableEstudiantes;
    private javax.swing.JButton btnActualizarProfesor;
    private javax.swing.JButton btnAgregarProfesor;
    private javax.swing.JButton btnBuscarProfesors;
    private javax.swing.JButton btnEditarProfesor;
    private javax.swing.JButton btnEliminarProfesor1;
    private javax.swing.JTable jTableProfesor;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private com.umg.api.ui.PanelRound panelRound1;
    private com.umg.api.ui.PanelRound panelRound3;
    private com.umg.api.ui.PanelRound panelRound4;
    private com.umg.api.ui.PanelRound panelRound5;
    private com.umg.api.ui.PanelRound panelRound6;
    private com.umg.api.ui.PanelRound panelRound7;
    private javax.swing.JTextField txtBuscarProfesors;
    // End of variables declaration//GEN-END:variables
}
